### ISSUE TITLE
Hpool not working

### ISSUE THREAD

**Issue by diowil** [gilnobrega/farmr#146]
Select action number: Failed to get HPool Info, make sure your auth_token is correct.
Unhandled exception:
Bad state: No element
#0      ListMixin.reduce (dart:collection/list.dart:222)
#1      HarvesterWallets.walletAggregate (package:farmr_client/harvester/wallets.dart:25)
#2      Farmer._getWinnerPlots (package:farmr_client/farmer/farmer.dart:331)
#3      Farmer.init (package:farmr_client/farmer/farmer.dart:460)
<asynchronous suspension>
#4      HPool.init (package:farmr_client/hpool/hpool.dart:77)
<asynchronous suspension>
#5      handleBlockchainReport (file:///home/runner/work/farmr/farmr/farmr.dart:433)
<asynchronous suspension>

**Comment by gilnobrega** [comment]
hpool mode is not officially supported anymore
