### ISSUE TITLE
Cmd window crashes in windows 11

### ISSUE THREAD

**Issue by ksevin** [gilnobrega/farmr#185]
When cpu load is high, farmer.exe window (windows 11) gives below errors and crashes.
Is there any solution to correct this issue?
 
Unhandled exception :
SqliteException(5): database is locked <code 5>
#0        throwException <package:sqlite3/src/impl/exception.dart:31>
<asyncroneous suspension>
……….
#7 handleBlockchainReport <file:///d:/a/farmr/farmr/farmr.dart:411>
<asyncroneous suspension>

**Comment by ksevin** [comment]
![B48E4F33-8655-4D54-80B6-A69166BCA399](https://user-images.githubusercontent.com/33321583/162582639-b0879c8f-5ba5-410d-a516-079ddddd9183.jpeg)

**Comment by epicalxyz** [comment]
Had this issue and solved it by deleting the .sqlite file inside .farmr/cache/ folder.
